# SonarQube Project Information
sonar.projectKey=javaparser-maven-sample
sonar.projectName=javaparser-maven-sample
sonar.projectVersion=1.0

# Source Code
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java Binaries
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Encoding
sonar.sourceEncoding=UTF-8

# JaCoCo Coverage Report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions (Optional)
sonar.exclusions=**/target/**

# SonarQube Server
#sonar.host.url=http://localhost:9000

# Authentication Token (Replace with your token)
sonar.token=squ_4bcb3bf347c1098b57d44d4c2ac5a24bcbd30b50
